# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  # ADD/CHANGE ME:
  networking.hostName = "lenovo";

  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7441969a-29b8-4459-8543-939e6d13a0aa";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3ABC-E543";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # vvvvv ADDED vvvv
  #fileSystems."/mnt/shared" = {
  #  device = "/dev/disk/by-uuid/C62F-33E3";
  #  fsType = "auto";
  #  options = [
  #    "nosuid"
  #    "nodev"
  #    "nofail"
  #    "x-gvfs-show"
  #    "uid=1000"
  #    "gid=1000"
  #    "umask=0000"
  #  ];
  # };
  # ^^^^ DONE ^^^^
  
  swapDevices = [ ];
    
  networking.useDHCP = lib.mkDefault true;
  
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
